- mosec/coordinator.py
- mosec/server.py
- src/main.rs
- tests/test_coordinator.py
- make rs controller exit only on terminate, and ignore interrupt
- make coordinators not log error when normal shutdown
- fix py graceful waiting bug
> fix shutdown

- mosec/protocol.py
* Decode ids to int to aid debugging
Logs Before
```text
received 10 tasks with ids: [b'\x00\x00\x00\x00', b'\x00\x00\x00\x01', b'\x00\x00\x00\x02', b'\x00\x00\x00\x03', b'\x00\x00\x00\x04', b'\x00\x00\x00\x05', b'\x00\x00\x00\x06', b'\x00\x00\x00\x07', b'\x00\x00\x00\x08', b'\x00\x00\x00\t']
```
Logs After
```text
received 10 tasks with ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
> decode binary for easier log information

- examples/distil_bert_server_pytorch.py
If model is on cuda device, the following lines will cause device error:
```python
with torch.no_grad():
result = self.model(
torch.nn.utils.rnn.pad_sequence(tensors, batch_first=True)
)[0]
```
The input should be converted to same device as model:
```python
torch.nn.utils.rnn.pad_sequence(tensors, batch_first=True).to(self.device)
```
> Make sure input and model are on the same device

- Cargo.lock
```
Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:      Upgrade to >=1.5.5
Dependency tree:
regex 1.5.4
└── tracing-subscriber 0.3.8
└── mosec 0.3.4
```
> fix audit: regex 1.5.4

- mosec/server.py
In the func `validate_int_ge_1`, it's checking if the number is greater or equal to 1. 
However in the current error message, it is said `must be greater than 1`, it may confuse the user a bit.
> update int_ge_1 validation error explanation

- pyproject.toml
this one has been moved to the optional extension
- https://github.com/PyCQA/pylint/pull/6448
- https://pylint.pycqa.org/en/stable/user_guide/messages/refactor/no-self-use.html?highlight=no-self-use
> fix: pylint no-self-use plugin

- .github/dependabot.yml
> Dependabot encountered the following error when parsing your `.github/dependabot.yml`:
> `The property '#/updates/2/commit-message/prefix' was not of a maximum string length of 15`
> chore: fix dependabot commit prefix

- Cargo.lock
- pyproject.toml
* https://github.com/mosecorg/mosec/actions/runs/2833223032 failed because `Cargo.lock` will be updated after installing, so the rest builds will work on the dirty git env
> fix CI release

- .github/workflows/package.yml
* https://github.com/actions/runner-images/issues/6002
* https://github.com/actions/runner-images/issues/5583
Since we are using `cibuildwheel`, it should be able to audit the wheel correctly.
> chore: update CI os version

- .github/workflows/package.yml
This has caused a lot of CI failures.
> chore: skip existing packages for pypi upload

- .github/workflows/check.yml
- .github/workflows/package.yml
- Makefile
- examples/python_side_metrics.py
- mosec/coordinator.py
- mosec/plugins/plasma_shm.py
- mosec/protocol.py
- mosec/server.py
- mosec/worker.py
- pyproject.toml
* fix #176 
* both `mypy` and `pyright` are kept here, I wonder if we should find a way to `make type-lint` success when at least one of `mypy` and `pyright` works
> feat: lint with pyright

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/main.rs
The main reason is that we don't need many CLI parser features as `clap` provided. But the binary size and compiling time are what we care about.
:crying_cat_face: result doesn't show much difference. At least, the rust-analyzer won't show any warning/error on the `clap` macro anymore.
* size reduced from `2.9M` to `2.7M` on Linux
* compiling time tested on my laptop (AMD 5800):
* debug: `21.69s` -> `19.27s`
* release: `26.89s` -> `24.41s`
> refact: use argh as the CLI argument parser

- .github/release.yml
Ref: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
We don't have a bot to automatically add the labels. But at least, we can exclude the PR made by the dependabot.
> chore: add release template

- Cargo.lock
- Cargo.toml
- README.md
- build.envd
- requirements/dev.txt
Signed-off-by: Keming <kemingyang@tensorchord.ai>
> feat: add envd as a dev env tool

- Cargo.lock
- Cargo.toml
- mosec/server.py
- src/tasks.rs
* fix https://github.com/mosecorg/mosec/issues/262
This is because when this connection is closed, the corresponding server tokio thread is also dead. So the created notifier channel is closed. Thus we need to delete the task since no one is going to use it.
Also, it's a bit ugly to put the metrics info in this task related method. Welcome other suggestions.
If it looks good, I'll also update the version and release a new one.
> fix: delete the task if the notifier channel is closed

- mosec/server.py
If we meet the Python spawn new process error, actually this dir is not created. So we can ignore this error.
Before:
```
2023-02-10 16:36:14,373 - 579501 - INFO - server.py:169 - Mosec Server Configurations: ['--path', '/tmp/mosec_bfad0b6f', '--capacity', '1024', '--timeout', '3000', '--wait', '10', '--address', '0.0.0.0', '--port', '8000', '--namespace', 'mosec_service', '--batches', '8']
2023-02-10 16:36:14,374 - 579501 - ERROR - server.py:334 - Traceback (most recent call last):   File "/home/keming/GitHub/mosec/mosec/server.py", line 331, in run     self._manage_coordinators()   File "/home/keming/GitHub/mosec/mosec/server.py", line 254, in _manage_coordinators     coordinator_process.start()   File …
```
> fix: ignore the rmtree error

- Cargo.lock
- Cargo.toml
- src/tasks.rs
They are not errors that users need to handle. We should use WARNING instead of ERROR.
> fix: warn about the timeout and channel is full

- Cargo.lock
- Cargo.toml
- README.md
- examples/custom_env.py
- examples/distil_bert_server_pytorch.py
- examples/echo.py
- examples/jax_single_layer.py
- examples/plasma_shm_ipc.py
- examples/python_side_metrics.py
- examples/resnet50_server_msgpack.py
- examples/stable_diffusion/server.py
- mosec/__init__.py
- mosec/args.py
- mosec/coordinator.py
- mosec/log.py
- mosec/plugins/plasma_shm.py
- mosec/protocol.py
- mosec/server.py
- mosec/worker.py
- pyproject.toml
- src/args.rs
- src/main.rs
- tests/test_coordinator.py
- tests/test_service.py
Target:
- provide a convenient way to set up the logging for both Python & Rust
- try to align the format of Python & Rust
- use JSON format for production, use colorful string for local debug
- filter Rust low level log like hyper and mio
Also, it's hard to set up the logging for Python because we heavily rely on multiprocessing. Thus the only way is to create the logger from a single source. For now, I think we can use a runtime environment variable since it will be inherited by all the children processing.
Welcome suggestions.
> feat: support colorful log for debug and json log for production

- README.md
- examples/README.md
- fix broken links
- rearrange README so that readers can easily refer to the codes when reading the steps
> docs: fix links and rearrange readme

- mosec/args.py
- mosec/server.py
- mosec/worker.py
- src/args.rs
- src/coordinator.rs
Since mosec supports dynamic batching for any stage, we should also support this.
This is a breaking change but the current interface remains the same. I think we can delete the legacy code before releasing v1.
> feat: enable configuring wait time for different stages

- examples/echo.py
- mosec/dry_run.py
For now, the `example` attribute should be a valid input for this worker. This means, if the worker has dynamic batching, then the input should be a list, vice versa.
> fix: align warmup example format in dry run

- Cargo.lock
- Cargo.toml
- mosec/server.py
- src/tasks.rs
Reproduce the bug:
`python examples/echo.py --debug`
```python
import concurrent.futures
import requests
import random
URL = "http://localhost:8000/inference"
def random_req(params, timeout):
resp = requests.post(URL, json=params, timeout=timeout)
return resp
with concurrent.futures.ThreadPoolExecutor(max_workers=16) as e:
futures = [
e.submit(random_req, {"time": 0.1}, random.random() / 5.0) for _ in range(1000)
]
for future in concurrent.futures.as_completed(futures):
try:
data = future.result()
except Exception as err:
print(err)
else:
print(data)
```
`python bad_req.py`
> fix: resolve deadlock when lots of client requests closed before response

- .github/workflows/package.yml
Since we have the merge queue, it can guarantee that the merged commits are correct.
> chore: skip the lint&test step in release

- mosec/__init__.py
- mosec/args.py
- mosec/coordinator.py
- mosec/dry_run.py
- mosec/errors.py
- mosec/log.py
- mosec/mixin/__init__.py
- mosec/mixin/msgpack_worker.py
- mosec/mixin/numbin_worker.py
- mosec/plugins/__init__.py
- mosec/plugins/plasma_shm.py
- mosec/protocol.py
- mosec/server.py
- mosec/worker.py
- tests/test_coordinator.py
- tests/test_protocol.py
- tests/utils.py
https://peps.python.org/pep-0008/#imports
Absolute import path is recommended as long as it is not too verbose, for readability.
> chore: use absolute import path

- mosec/coordinator.py
- mosec/dry_run.py
- mosec/log.py
- mosec/protocol.py
- mosec/server.py
Fix Issue #289 
Before:
It's hard to differentiate logs from user, mosec python,mosec rust.  
```bash
{"timestamp": "2023-03-23T 14:50 : 33.244310+0800", "level": "INFO", "fields": {"message": "Starting server"}, "target": "main. py:<module>"}
{"timestamp": "2023-03-23T 14:50 : 36.199222+0800", "level": "INFO", "fields": {"message": "<3|Postprocess|2> socket connected to /tmp/mosec_e19e5a63/ipc_3. socket"}, "target": "protocol. py: open"}
{"timestamp": "2023-03-23T 14:50 : 36.199435642+ 08:00 ","level": "INFO","fields":{"message": "socket accepted connection from","addr": " (unnamed)"},"target": "mosec:: protocol"}
```
After:
logs field `target` from user startwith 'user::'.
logs field `target` from mosec python and mosec rust startwith 'mosec::'
```bash
{"timestamp": "2023-03-23T 15:00 : …
```
> Add prefix to differentiate Mosec & user logs

- Cargo.lock
- Cargo.toml
- src/main.rs
- tests/bad_req.py
- related to #273 
`axum` supports SSE and WebSocket. Will implement SSE later.
> feat: use axum instead of pure hyper

- mosec/coordinator.py
- mosec/errors.py
- mosec/protocol.py
- mosec/server.py
- src/main.rs
- src/protocol.rs
- src/tasks.rs
- tests/test_coordinator.py
- tests/test_timeout_service.py
- tests/timeout_service.py
refer to [feat: raise TimeoutError when the forward doesn't return in a long time #298](https://github.com/mosecorg/mosec/issues/298)
raise MosecTimeoutError when the forward doesn't return in a long time.
Since there's already a TimeoutError inherited from OSError in python stdlib, I use `MosecTimeoutError` instead of `TimeoutError`.
Unable to set timer for `worker.forward` function, it may block that worker. 
In Rust side, there's a `ServiceError::Timeout` error to detect if the worker runs too long.
Developers can set timeout for workers of each stage like `server.append_worker(Inference, timeout=2)`.
If `worker.forward` runs too long, it will raise MosecTimeoutError, send 408 request timeout error to Rust side.
In response.text, users can see  `408 mosec timeout error: 'forward' …
> feat: Set timeout for worker.forward

- .lycheeignore
- examples/monitor/docker-compose.yml
- examples/monitor/dockerfile
- examples/monitor/mosec_dashboard.json
- examples/monitor/mosec_dashboard.yml
- examples/monitor/mosec_datasource.yml
- examples/monitor/prometheus.yml
- examples/monitor/python_side_metrics.py
- examples/monitor/readme.md
- examples/python_side_metrics.py
- examples/resnet50_server_msgpack.py
ref to #297
Provide a whole monitoring demo with Prometheus and Grafana.
`cd examples/monitor` and run `docker-compose up`
Then you can open [Grafana](http://localhost:3000/d/4vV0bzE4z/mosec?orgId=1) to see the mosec dashboard
or open [Prometheus](http://127.0.0.1:9090) to query the metrics collected in mosec.
> feat: add monitoring demo

- .github/workflows/nightly.yml
I have no idea what happened to macOS.
> chore: only enable nightly test for Linux

- examples/plasma_shm_ipc.py
- mosec/mixin/plasma_worker.py
- requirements/dev.txt
- tests/mixin_ipc_shm_service.py
- tests/test_service.py
Although plasma can handle the `np.ndarray` and common Python type serde, I think it's better to make it explicit.
This example is closer to the real scenario.
> fix: plasma mixin should use super serde with shm storage

- .github/workflows/check.yml
- Makefile
- build.envd
- mosec/args.py
- mosec/log.py
- mosec/server.py
- pyproject.toml
- tests/test_service.py
Previously, if I run `pytest tests/test_utils.py` it will also check if port 8000 is free.
> fix: args should only be checked when server is used

- mosec/dry_run.py
- mosec/env.py
- mosec/manager.py
- mosec/server.py
- src/args.rs
- src/main.rs
- src/protocol.rs
- tests/square_service.py
- tests/test_coordinator.py
- tests/test_service.py
- Refactor of `Server` and `dry_run`
- Support dynamic route by adding `endpoint` argument to `Server`
Refactor:
```mermaid
graph LR
1[Server] --> 2[Controller]
1[Server] --> 3[CoordinatorManager]
2[Controller] -->|start\nhalt\ngenerate args| 4[Rust process]
3[CoordinatorManager] --> 5>WorkerRuntime 1]
3[CoordinatorManager] --> 6>WorkerRuntime 2]
3[CoordinatorManager] --> 7>WorkerRuntime 3]
5>WorkerRuntime 1] -->|start\nvalidate args\nhealth check| 8[Coordinator process * num]
6>WorkerRuntime 2] -->|start\nvalidate args\nhealth check| 9[Coordinator process * num]
7>WorkerRuntime 3] -->|start\nvalidate args\nhealth check| 10[Coordinator process * num]
```
API:
```python
server = Server(endpoint="/v1/inference")
server.append_worker(Service)
server.run()
```
> feat: support dynamic inference route

- Makefile
- examples/jax_single_layer_cli.py
- examples/resnet50_client_msgpack.py
- examples/stable_diffusion/client.py
- mosec/args.py
- mosec/dry_run.py
- mosec/mixin/plasma_worker.py
- mosec/runtime.py
- mosec/server.py
- pyproject.toml
- setup.py
- tests/bad_req.py
- tests/mock_socket.py
- tests/services/bad_service.py
- tests/services/mixin_ipc_shm_service.py
- tests/services/mixin_numbin_service.py
- tests/services/mixin_typed_service.py
- tests/services/openapi_service.py
- tests/services/square_service.py
- tests/services/sse_service.py
- tests/services/timeout_service.py
- tests/test_coordinator.py
- tests/test_log.py
- tests/test_protocol.py
- tests/test_service.py
- tests/test_utils.py
- tests/utils.py
- align the naming of `PyRuntimeManager` and `RsRuntimeManager`
- fix the test lint, close #136 
I tried `ruff` but I feel we can wait for it to be more mature.
> chore: align the naming, fix the test lint

- .readthedocs.yaml
- ModuleNotFoundError in https://mosec.readthedocs.io/en/latest/reference/arguments.html
- https://mosec.readthedocs.io/en/latest/reference/interface.html doesn't contain all the interfaces, compared to https://mosecorg.github.io/mosec/reference/interface.html
> docs: fix readthedocs build config

- Makefile
- README.md
- examples/stable_diffusion/server.py
- requirements/dev.txt
- setup.py
* Too-long readme is a bit distracting
> chore: use collapsible readme

- .github/actions/cache/action.yml
- .github/workflows/package.yml
- pyproject.toml
- fix #507 
This PR also disabled the build for "musllinux" and "PyPy" to save some storage space on PyPI.
I haven't tested the PyPy version. As for the musl, I don't know if it's necessary to keep it.
> chore: support macOS ARM release

- .github/workflows/links.yml
- docs/source/examples/embedding.md
- mosec/dry_run.py
- mosec/mixin/typed_worker.py
- src/routes.rs
- msgspec can decode `msgspec.Struct/dataclass/attr/etc`, no need to check the class type
> chore: fix typos and broken links

- examples/rerank/server.py
import __future__ annotation will break mosec.utils.parse_func_type. the __main__.Request would be changed to 'Request':
```
2024-06-15T00:55:54.001558Z  WARNING mosec::coordinator.py:300 [1869971]: Traceback (most recent call last):
File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 274, in coordinate     data = [
File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 275, in <listcomp>     self.decode(payload, state)
File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 243, in decode     self.worker.deserialize(payload)
File "/home/user/mosec/lib/python3.10/site-packages/mosec/mixin/typed_worker.py", line 45, in deserialize     return msgspec.msgpack.decode(data, type=self._input_typ)
TypeError: Type …
```
> Fix rerank server error

- Cargo.lock
- Cargo.toml
- mosec/server.py
- mosec/utils/types.py
- pyproject.toml
- requirements/dev.txt
- fix https://github.com/mosecorg/mosec/issues/535
`from __future__ import annotations` will enable the annotations lazy evaluation which changes all the annotations into strings. We have to eval these strings to get the real objects.
> fix: annotations lazy evaluation

- mosec/coordinator.py
- mosec/errors.py
- mosec/protocol.py
- tests/test_coordinator.py
- There is a typo on variable name (`HTTPStautsCode`)
> refactor: HTTPStautsCode -> HTTPStatusCode

- .github/workflows/check.yml
- Makefile
- mosec/log.py
- mosec/runtime.py
- pyproject.toml
- requirements/dev.txt
- requirements/mixin.txt
- tests/test_coordinator.py
- related to https://github.com/conda-forge/mosec-feedstock/pull/14
We already release 3.13 since it has compatible ABI as the final release. (this is the default behavior for cibuildwheel).
However, `pkg_resources` is deprecated.
- https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename
> fix: replace pkg_resources with importlib

- Cargo.lock
- Cargo.toml
- README.md
- examples/stable_diffusion/server.py
- requirements/dev.txt
- src/main.rs
- src/routes.rs
- src/tasks.rs
- tests/test_service.py
`hyper` can serve the traffic with HTTP/1.1 & HTTP/2.
Verified with `curl -I --http2-prior-knowledge -w '%{http_version}\n' http://127.0.0.1:8000/metrics`.
> feat: add http/2 support

- docs/source/conf.py
Clicking on `edit this page` button on top of the page when not in the `latest` version of the docs redirects to a non-existing page
> [Docs] Add source_edit_link to point to the correct path

- .github/workflows/links.yml
OpenAI forbid `lychee`, let's ignore the 403 error for now.
- https://github.com/lycheeverse/lychee/issues/1157
> chore: upgrade lychee action and accept 403 forbidden

- .github/workflows/check.yml
- Cargo.lock
- Cargo.toml
- mosec/server.py
- requirements/dev.txt
- src/apidoc.rs
- tests/services/mixin_ipc_shm_service.py
Previously, the `GUARD_CHECK_INTERVAL = 1` will affect the shutdown time:
- receive signal, set the shutdown to true
- wait until the next check cycle to exit (`sleep(GUARD_CHECK_INTERVAL)`)
This will get an average of 0.5s extra wait time to exit, which could be treated as an abnormal situation for users.
I have checked the average check time for that loop, it's about 0.05-0.09 ms. So decreasing it to 0.1s should be okay.
BTW, Python `sys.getswitchinterval()` is 5ms.
> feat: decrease the guard check interval, bump version

- Cargo.lock
- Cargo.toml
- README.md
- docs/source/examples/compression.md
- docs/source/examples/index.md
- examples/segment/client.py
- examples/segment/server.py
- mosec/args.py
- pyproject.toml
- requirements/dev.txt
- src/config.rs
- src/main.rs
- src/routes.rs
- tests/test_service.py
> feat: support gzip & zstd compression

- .github/workflows/check.yml
- Cargo.lock
- Cargo.toml
- requirements/dev.txt
- requirements/mixin.txt
- axum 0.8 breaks a lot of projects, but we're good since we're heavily using hyper directly
- mixin dependencies have 3.13 release now, we can enable the test
> feat: bump axum to 0.8, enable 3.13 test

- .github/workflows/deny.yml
- Dockerfile
- deny.toml
- use latest py311 in dockerfile
- fix the binary path (when the cmd skips bashrc)
- cargo-deny trigger
> fix: dockerfile mosec bin path & cargo-deny trigger

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .github/workflows/page.yml
- CONTRIBUTING.md
- Makefile
- README.md
> docs: add pixi
