.github/workflows/check.yml, .github/workflows/page.yml, Makefile, docs/argument.md, mkdocs.yml, mosec/args.py, scripts/gen_docs_args.py, setup.py
- use gen-files to dynamically generate docs for argument
=> add docs for args

src/main.rs, src/protocol.rs, src/tasks.rs
=> Fix issue 53: add rust unit test

scripts/gen_docs_args.py
minor fix for [this page](https://mosecorg.github.io/mosec/argument/)
=> fix doc-gen

.github/workflows/check.yml
Refs:
* https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
* https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/5
=> run the lint and test when it's ready for review

.github/workflows/package.yml
* use artifact to publish pypi
* use cache and source code to publish cargo
=> fix publish ci

.github/workflows/check.yml, .github/workflows/package.yml, .github/workflows/page.yml
fix the git secure bug:
* https://github.com/actions/checkout/releases/tag/v3.0.1
=> change to checkout@v3

CITATION.cff
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
=> add citation

mosec/worker.py
https://stefan.sofa-rockers.org/2020/10/28/raise-from/
=> feat: exception traceback

examples/plasma_shm_ipc.py
=> fix: convert size from str to int

README.md, docs/example/Env.md, examples/custom_env.py, examples/python_side_metrics.py, tests/test_service.py
=> add custom env example

.github/workflows/check.yml
=> fix ci pull request path condition

.github/workflows/package.yml, scripts/build.sh
=> fix: only build source distribution once

.github/workflows/check.yml
=> fix: always run test since it's free for public repo now

requirements/doc.txt
=> fix: mkdocs interface dependencies

.github/dependabot.yml
=> feat: scan github actions every week

.github/workflows/package.yml
=> fix: pypi source distribution

pyproject.toml
=> chore: add more pypi categories

Cargo.toml
=> release 0.4.0

examples/echo.py, mosec/coordinator.py, src/protocol.rs
=> fix: log warn abnormal tasks

mosec/errors.py, mosec/mixin/__init__.py, mosec/mixin/msgpack_worker.py, mosec/worker.py, requirements/plugin.txt, tests/test_coordinator.py
=> feat: msgpack mixin

docs/example/pytorch.md
=> doc: fix resnet example

README.md, pyproject.toml
=> chore: add py version support badge

examples/distil_bert_server_pytorch.py
=> fix: mypy type check for type alias

Cargo.lock, Cargo.toml, README.md
=> chore: fix rs version and discord link

Cargo.lock, Cargo.toml
=> chore(cargo): refine required features

mosec/server.py
=> chore: rm socket after shutdown

mosec/protocol.py
=> feat: improve the performance of IPC protocol send

mosec/args.py, mosec/coordinator.py, setup.py
Signed-off-by: Zichen [lkevinzc@gmail.com](lkevinzc@gmail.com)
=> refact: use traceback for warmup error

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
=> chore: add devcontainer configs

.github/workflows/check.yml
=> chore: trigger ci if py requirements changed

Cargo.lock, Cargo.toml, Makefile, mosec/coordinator.py, mosec/worker.py, tests/test_coordinator.py
=> fix: worker property

README.md, docs/example/stable_diffusion.md, examples/__init__.py, examples/stable_diffusion/build.envd, examples/stable_diffusion/client.py, examples/stable_diffusion/server.py, mkdocs.yml, src/metrics.rs
=> docs: add a stable diffusion serving example

examples/plasma_shm_ipc.py, mosec/protocol.py
=> feat: warning for the IPC data size

Cargo.lock, Cargo.toml, mosec/args.py
* fix https://github.com/mosecorg/mosec/issues/267
=> fix: only parse known arguments

Cargo.lock, Cargo.toml, examples/echo.py, mosec/coordinator.py
=> fix: return equal number of error payloads

examples/custom_env.py, examples/echo.py, mosec/coordinator.py, mosec/server.py, src/coordinator.rs, src/main.rs, src/protocol.rs, src/tasks.rs
Welcome suggestions.
- fix #275
=> feat: improve the log msg to make it more friendly

README.md
=> feat: Add adopters

examples/echo.py, mosec/args.py, mosec/dry_run.py, mosec/env.py, mosec/server.py
- fix https://github.com/mosecorg/mosec/issues/296
=> feat: support dry run the service

Cargo.lock, Cargo.toml, README.md, examples/stable_diffusion/server.py, mosec/args.py, mosec/env.py
- fix https://github.com/mosecorg/mosec/issues/281
=> feat: support set up the arguments through environment variables

.github/workflows/check.yml, .github/workflows/package.yml, Makefile, mosec/mixin/__init__.py, mosec/mixin/numbin_worker.py, requirements/dev.txt, requirements/plugin.txt, tests/mixin_numbin_service.py, tests/test_coordinator.py, tests/test_service.py
=> feat: add numbin as an IPC mixin

.github/workflows/nightly.yml, .github/workflows/page.yml, tests/bad_req.py
- refer to https://github.com/mosecorg/mosec/pull/311
This cannot 100% detect the deadlock. But I guess it's helpful.
=> chore: add nightly bad req test

Cargo.lock, Cargo.toml, examples/jax_single_layer_cli.py, examples/resnet50_client_msgpack.py, examples/stable_diffusion/client.py, mosec/coordinator.py, tests/bad_req.py, tests/test_service.py, tests/test_timeout_service.py, tests/timeout_service.py, tests/utils.py
- failed CI https://github.com/mosecorg/mosec/actions/runs/4589668603/jobs/8104732633
=> fix: avoid timeout test failing and orphan service in CI

README.md
=> chore: add image

Cargo.lock, Cargo.toml, src/main.rs, src/metrics.rs, src/protocol.rs
refer to #186
switch from https://github.com/tikv/rust-prometheus to https://github.com/prometheus/client_rust
=> refactor: switch to official prometheus client

Cargo.lock, Cargo.toml, MANIFEST.in, Makefile, license.json, mosec/mixin/msgpack_worker.py, requirements/plugin.txt
refer to https://github.com/conda-forge/staged-recipes/pull/22367#pullrequestreview-1408248017
=> chore: add dependencies license file

examples/distil_bert_server_pytorch.py, mosec/mixin/msgpack_worker.py, mosec/mixin/typed_worker.py, mosec/server.py, mosec/worker.py, src/args.rs, src/main.rs, tests/test_service.py
=> feat: add content type to the inference response header

.readthedocs.yaml, Makefile, docs/source/index.md
benefits:
- SEO https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#best-practices-for-documentation-seo
- multiple versions
=> chore: add readthedoc support

Cargo.lock, README.md, src/metrics.rs, src/routes.rs, src/tasks.rs
=> feat: add endpoint label to the code metrics

.github/workflows/package.yml
ref:
- https://docs.github.com/en/webhooks/webhook-events-and-payloads#release
=> chore: fix the docker image tags

Cargo.lock, Cargo.toml, README.md, examples/embedding/client.py, examples/embedding/server.py, mosec/log.py, src/main.rs
- fix https://github.com/mosecorg/mosec/issues/468
=> feat: use utc time for log

.github/workflows/nightly.yml, Cargo.lock, Cargo.toml, examples/custom_env.py, examples/embedding/server.py, mosec/mixin/msgpack_worker.py, mosec/mixin/numbin_worker.py, mosec/mixin/plasma_worker.py, mosec/mixin/redis_worker.py, mosec/mixin/typed_worker.py, src/main.rs, src/routes.rs, tests/test_utils.py
It doesn't have a user-friendly graceful shutdown interface.
~~Waiting for~~:
- https://github.com/hyperium/hyper-util/pull/66
- https://github.com/tokio-rs/axum/pull/2398
=> fix: upgrade to hyper 1

.github/actions/cache/action.yml, .github/workflows/check.yml, .github/workflows/package.yml, Makefile, requirements/mixin.txt
1. add macOS ARM test
2. run lint and test in parallel to make it faster
3. upload the sdist before the `cargo publish`, just in case I forgot to update the version in the `Cargo.toml`
=> test: add arm in ci

docs/source/examples/embedding.md
=> docs: update embedding.md

.github/workflows/check.yml, pyproject.toml
- related to https://github.com/pypa/setuptools/pull/4696
=> chore: fix the dynamic extra dependencies

docs/source/conf.py, docs/source/robots.txt, requirements/doc.txt
=> docs: add sitemap and robots

Cargo.lock, Cargo.toml, mosec/mixin/plasma_worker.py
MSRV is found by [cargo-msrv](https://github.com/foresterre/cargo-msrv).
- related to https://github.com/mosecorg/mosec/issues/507#issuecomment-2559141719
=> chore: add MSRV

.github/CODEOWNERS, .github/dependabot.yml
The dependabot config file will remove the reviewers option.
=> chore: add code owner
